# Generated by Django 5.2.6 on 2025-09-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TastyBiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(default='', max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
