# Generated by Django 5.2.6 on 2025-09-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TastyBiteapp', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='TastyBiteapp.customer')),
                ('items', models.ManyToManyField(related_name='cart', to='TastyBiteapp.item')),
            ],
        ),
    ]
